name: CMake

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  build:
    strategy:
      matrix:
        cmake_build_type: [Asan, Release]

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential
          sudo apt install clang clang-format clang-tidy

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
          key: ${{ github.job }}-${{ matrix.cmake_build_type }}

      - name: Prepare
        run: CC=clang CXX=clang++ bash ci/prepare.bash ${{ matrix.cmake_build_type }}

      - name: Precommit
        if: matrix.cmake_build_type == 'Release'
        run: bash ci/precommit.bash check --style

      - name: Precommit (no style checks)
        if: matrix.cmake_build_type == 'Asan'
        run: bash ci/precommit.bash check --no-style
