# CMP0007: list command no longer ignores empty elements.
if(POLICY CMP0007)
    cmake_policy(SET CMP0007 NEW)
endif()

function(exec_check)
    execute_process(COMMAND ${ARGV0} ${ARGV1} ${ARGV2}
        OUTPUT_VARIABLE out
        ERROR_VARIABLE  err
        RESULT_VARIABLE result)
        if(ARGV4 EQUAL 0)
        if(NOT (out STREQUAL ARGV3) OR NOT (result EQUAL 0))
            string(REPLACE "/" ";" name_components  ${ARGV0})
            list(GET name_components -1 name)
            if(NOT out)
                set(out "<empty>")
            endif()
            if(NOT err)
                set(err "<empty>")
            endif()
            message(FATAL_ERROR "\nError running \"${name}\"\n*** Output: ***\n${out}\n*** Expected output: ***\n${ARGV3}\n*** Error: ***\n${err}\n*** Error code: ***\n${result}\n")
        endif()
    else()
        if(NOT (result EQUAL ARGV4))
            string(REPLACE "/" ";" name_components  ${ARGV0})
            list(GET name_components -1 name)
            if(NOT out)
                set(out "<empty>")
            endif()
            if(NOT err)
                set(err "<empty>")
            endif()
            message(FATAL_ERROR "\nError running \"${name}\"\n*** Output: ***\n${out}\n*** Error: ***\n${err}\n*** Error code: ***\n${result}\n*** Expected error code: ***\n${ARGV4}\n")
        endif()
    endif()
endfunction()

file(STRINGS ${TEST_DIR}/section SECTION)
file(STRINGS ${TEST_DIR}/err_code ERR_CODE)
file(STRINGS ${TEST_DIR}/output OUTPUT)
exec_check(${ELF64_LOADER} ${TEST_DIR}/input ${SECTION} ${OUTPUT} ${ERR_CODE})
